from astropy.time import Time

from . import _mixins
from ._tagged import TaggedListNode, TaggedObjectNode, TaggedScalarNode


class Guidewindow(TaggedObjectNode): ...


class Ramp(TaggedObjectNode): ...


class RampFitOutput(TaggedObjectNode): ...


class WfiScienceRaw(TaggedObjectNode): ...


class WfiImage(TaggedObjectNode): ...


class WfiMosaic(TaggedObjectNode): ...


class WfiMode(_mixins.WfiModeMixin, TaggedObjectNode): ...


class Exposure(TaggedObjectNode): ...


class Program(TaggedObjectNode): ...


class Observation(TaggedObjectNode): ...


class Ephemeris(TaggedObjectNode): ...


class Visit(TaggedObjectNode): ...


class Photometry(TaggedObjectNode): ...


class SourceDetection(TaggedObjectNode): ...


class Coordinates(TaggedObjectNode): ...


class Aperture(TaggedObjectNode): ...


class Pointing(TaggedObjectNode): ...


class Target(TaggedObjectNode): ...


class VelocityAberration(TaggedObjectNode): ...


class Wcsinfo(TaggedObjectNode): ...


class Guidestar(TaggedObjectNode): ...


class L2CalStep(TaggedObjectNode): ...


class L3CalStep(TaggedObjectNode): ...


class OutlierDetection(TaggedObjectNode): ...


class SkyBackground(TaggedObjectNode): ...


class Resample(TaggedObjectNode): ...


class IndividualImageMeta(TaggedObjectNode): ...


class MosaicBasic(TaggedObjectNode): ...


class MosaicAssociations(TaggedObjectNode): ...


class MosaicWcsinfo(TaggedObjectNode): ...


class AbvegaoffsetRef(TaggedObjectNode): ...


class ApcorrRef(TaggedObjectNode): ...


class DarkRef(TaggedObjectNode): ...


class DistortionRef(TaggedObjectNode): ...


class EpsfRef(TaggedObjectNode): ...


class FlatRef(TaggedObjectNode): ...


class GainRef(TaggedObjectNode): ...


class InverselinearityRef(TaggedObjectNode): ...


class IpcRef(TaggedObjectNode): ...


class LinearityRef(TaggedObjectNode): ...


class MaskRef(TaggedObjectNode): ...


class PixelareaRef(TaggedObjectNode): ...


class ReadnoiseRef(TaggedObjectNode): ...


class RefpixRef(TaggedObjectNode): ...


class SaturationRef(TaggedObjectNode): ...


class SuperbiasRef(TaggedObjectNode): ...


class WfiImgPhotomRef(TaggedObjectNode): ...


class Associations(TaggedObjectNode): ...


class RefFile(TaggedObjectNode): ...


class SourceCatalog(TaggedObjectNode): ...


class SegmentationMap(TaggedObjectNode): ...


class MosaicSourceCatalog(TaggedObjectNode): ...


class MosaicSegmentationMap(TaggedObjectNode): ...


class Fps(TaggedObjectNode): ...


class FpsCalStep(TaggedObjectNode): ...


class FpsExposure(TaggedObjectNode): ...


class FpsGroundtest(TaggedObjectNode): ...


class FpsGuidestar(TaggedObjectNode): ...


class FpsStatistics(TaggedObjectNode): ...


class FpsRefFile(TaggedObjectNode): ...


class FpsWfiMode(TaggedObjectNode): ...


class Tvac(TaggedObjectNode): ...


class TvacCalStep(TaggedObjectNode): ...


class TvacExposure(TaggedObjectNode): ...


class TvacGroundtest(TaggedObjectNode): ...


class TvacGuidestar(TaggedObjectNode): ...


class TvacStatistics(TaggedObjectNode): ...


class TvacRefFile(TaggedObjectNode): ...


class TvacWfiMode(TaggedObjectNode): ...


class MsosStack(TaggedObjectNode): ...


class CalLogs(TaggedListNode): ...


class CalibrationSoftwareVersion(str, TaggedScalarNode): ...


class Filename(str, TaggedScalarNode): ...


class FileDate(Time, TaggedScalarNode): ...


class ModelType(str, TaggedScalarNode): ...


class Origin(str, TaggedScalarNode): ...


class PrdSoftwareVersion(str, TaggedScalarNode): ...


class SdfSoftwareVersion(str, TaggedScalarNode): ...


class Telescope(str, TaggedScalarNode): ...


class FpsCalibrationSoftwareVersion(str, TaggedScalarNode): ...


class FpsFilename(str, TaggedScalarNode): ...


class FpsFileDate(Time, TaggedScalarNode): ...


class FpsModelType(str, TaggedScalarNode): ...


class FpsOrigin(str, TaggedScalarNode): ...


class FpsPrdSoftwareVersion(str, TaggedScalarNode): ...


class FpsSdfSoftwareVersion(str, TaggedScalarNode): ...


class FpsTelescope(str, TaggedScalarNode): ...


class TvacCalibrationSoftwareVersion(str, TaggedScalarNode): ...


class TvacFilename(str, TaggedScalarNode): ...


class TvacFileDate(Time, TaggedScalarNode): ...


class TvacModelType(str, TaggedScalarNode): ...


class TvacOrigin(str, TaggedScalarNode): ...


class TvacPrdSoftwareVersion(str, TaggedScalarNode): ...


class TvacSdfSoftwareVersion(str, TaggedScalarNode): ...


class TvacTelescope(str, TaggedScalarNode): ...
