from typing import Annotated, ClassVar

from pydantic import ConfigDict, Field

from roman_datamodels.pydantic import _core, _defaults
from roman_datamodels.pydantic import _uri as uri

__all__ = ["SourceDetection"]


class SourceDetection(_core.BaseRomanTaggedModel):
    _uri: ClassVar = uri.asdf_uri.SOURCE_DETECTION.value
    _tag_uri: ClassVar = uri.asdf_tag_uri.SOURCE_DETECTION.value

    _optional_fields: ClassVar = ("tweakreg_catalog_name",)

    model_config = ConfigDict(
        title="Source catalog generated by the Source Detection Step for TweakReg",
    )

    tweakreg_catalog_name: Annotated[
        str,
        Field(
            default_factory=_defaults.default_constant_factory("filename_tweakreg_catalog.asdf"),
        ),
    ]
