from typing import Annotated, ClassVar

from pydantic import ConfigDict, Field

from ..._core import BaseRomanTaggedModel
from ..._defaults import default_constant_factory
from ..._uri import asdf_tag_uri, asdf_uri

__all__ = ["SourceDetection"]


class SourceDetection(BaseRomanTaggedModel):
    _uri: ClassVar = asdf_uri.SOURCE_DETECTION.value
    _tag_uri: ClassVar = asdf_tag_uri.SOURCE_DETECTION.value

    _optional_fields: ClassVar = ("tweakreg_catalog_name",)

    model_config = ConfigDict(
        title="Source catalog generated by the Source Detection Step for TweakReg",
    )

    tweakreg_catalog_name: Annotated[
        str,
        Field(
            default_factory=default_constant_factory("filename_tweakreg_catalog.asdf"),
        ),
    ]
